### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by soopercool101** [kwsch/PKHeX.Mobile#14]
Appears to be an issue with linking the DLL. Exact steps from the readme were followed.

```
Mono.Linker.MarkException: Error processing method: 'System.Int32 PKHeX.Core.AutoMod.PokeTrainerDetails::get_Country()' in assembly: 'PKHeX.Core.AutoMod.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 PKHeX.Core.PKM::get_Country()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()
```

**Comment by soopercool101** [comment]
I now realize this is a duplicate of #13 but the linked commit does not appear to have fixed the issue. Is there a reason that a prebuilt DLL is used over an in-solution fork of PKHeX.Core?

**Comment by kwsch** [comment]
Was broken by this commit: https://github.com/kwsch/PKHeX.Mobile/commit/48f4a6f74b5afe00ae04f310024c95665d9ca881

Note in the commit message: `Legalization won't work until dll dependency is updated`

Probably needs the dll from this release: https://github.com/architdate/PKHeX-Plugins/releases/tag/20.08.07
